# Generated by Django 4.2.4 on 2023-08-28 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_ranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['-score']},
        ),
    ]
