# Generated by Django 4.2.4 on 2023-08-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_alter_ranking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['-total_score', '-crypto_score', '-web_score', '-system_score', '-linux_score']},
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='score',
        ),
        migrations.AddField(
            model_name='ranking',
            name='crypto_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='linux_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='system_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='web_score',
            field=models.IntegerField(default=0),
        ),
    ]
