# Generated by Django 4.2.4 on 2023-08-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_alter_ranking_options_remove_ranking_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['-score', 'category']},
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='crypto_score',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='linux_score',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='system_score',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='web_score',
        ),
        migrations.AddField(
            model_name='ranking',
            name='category',
            field=models.CharField(choices=[('Crypto', 'Crypto'), ('Linux', 'Linux'), ('System', 'System'), ('Web', 'Web'), ('Total', 'Total')], default='Total', max_length=100),
        ),
        migrations.AddField(
            model_name='ranking',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
