# Generated by Django 4.2.4 on 2023-08-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_alter_ranking_options_remove_ranking_crypto_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
