# Generated by Django 4.2.4 on 2023-10-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
