# Generated by Django 4.2.4 on 2023-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('score', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=100)),
                ('ssh_path', models.CharField(max_length=100)),
            ],
        ),
    ]
